var profileUrlConfig = {
    profileApi: "",
    profileBase: "/api-profile/v1/identity/",
    profileSecurityCustomLogin:  "/api-profile/v1/security/",
    profileBaseUrl: "/api-profile/v1/",
    profilePictureBaseUrl: "/api-profile/v1/profile/",
    resources: {
        profile:"profile/",
        platform:"platform/",
        name: "/names",
        contact: "/contacts",
        address: "/addresses",
        addresses: "/addresses?effectivedate=",
        personalInfo: "/personals",
        personalStatusUpdate: "/personal-status",
        personal: "/personals?uniqueId=",
        workprofile: "/work-profiles",
        personalstatus: "/personals?effectiveDate=",
        personalStatus: "/ssn",
        emergencyContact: "/emergency-contacts",
        employmentDetails: "/employee-details",
        bussinesTitleChange: "business-title",
        locations: "locations",
        departments: "departments",
        employmentChange: "employment-change",
        jobs: "jobs",
        companies: "companies",
        citizenship: "/citizenship",
        picture: "/photos",
        employment: "/employment-info",
        compensation: "/compensation",
        identity: "/identity",
        identityInfo: "/identity-info"
    }
};
