var globalUrlConfig = {
    globalApi: "",
    globalBase: "/api-config/v1",
    globalCalenderBase:"api-company-holiday-calendar/v1",
    ssoArtifactBase: "/api-sso/v1/sso/",
    resources: {
        company: "/company",
        global: "/global",
        usCountryCode: "/US",
        payFreq: "/pay-frequencies",
        earnType: "/earn-types",
        transferReasons: "/transfer-reasons",
        payChangeReasons: "/paychange-reasons",
        jobRecReasons: "/job-reclassification-reasons",
        promotionReasons: "/promotion-reasons",
        demotionReasons: "/demotion-reasons",
        compensationTypes: "/compensation-types",
        flsa: "/flsa-codes",
        jobs: "/jobs",
        ethnicity: "/ethnicities",
        workersCompLookUp: "/workers-comp",
        locations: "/locations",
        locationcode: "/location-code",
        departments: "/departments",
        positions:"positions",
        countries: "/countries",
        payGroups:'/paygroups',
        states: "/states",
        directManager: "direct-managers",
        ssoArtifacts: "/sso-artifacts/",
        rolesRestrict:"/role-restrictions",
        calender:"/holidaycalendar",
        activeCompany:"/activeCompany",
        fetchRoles:"/fetchUserRole",
        newHolidays:"/holidays",
        earnTypeDates: "/earn-types-date",
        workersCompPolicies: "/workers-comp-policies",
        tippedCodes:"/tipped-codes",
        trinetRefLibUrl:"/reflib",
        trinetNavigatorSuiteUrl: "/chr"
    }
};
