var manageEmpUrlConfig = {
    manageEmpApi: "",
    manageBaseUrl: "/api-employee/v1",
    newManageBaseUrl: "/api-employee/v2",
    newRolesBaseUrl: "/api-employee/v1.1",
    resources: {
        extLeave: "/extended-leave",
        extendedLeaveCds: "/extendedleave-cds",
        timeOff: "/timeoff",
        timeOffHistory: "/timeoff-history?excludeHistory=true",
        returnLeave: "/return-extended-leave",
        allEmp: "/employees",
        company: "/company",
        manageEmployees: "/manage-employees",
        forms: "/forms",
        assignManager: "/AssignManager",
        assignManagerNew:"/assign-manager",
        managegroup: "/manage-group",
        managegroupdep: "?include=DEP&offset=0&limit=20&sortBy=name&sortOrder=asc",
        managegrouploc: "?include=LOC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        managegroupdeploc: "?include=DEP,LOC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        managegroupall:"?include=DEP,LOC,LPC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        managegroupdeplpc:"?include=DEP,LPC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        managegrouploclpc:"?include=LOC,LPC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        managegrouplpc: "?include=LPC&offset=0&limit=5&sortBy=name&sortOrder=asc",
        groupchanges: "/group-changes?offset=0&limit=10",
        groupchangeohioemail: "/ohioemail",
        groupchangesdep: "/group-changes/DEP?effectiveDate=",
        groupchangesloc: "/group-changes/LOC?effectiveDate=",
        groupchangeslpc: "/group-changes/LPC?effectiveDate=",
        employee: "/manage-employee",
        termReport: "Termination",
        userRoles:"/user-roles",
        termReportList: "/terminationReportList",
        payReport: "beginendreport",
        payReportList: "/beginEndReportList",
        moneyPay: "/additional-payments",
        payFreq: "/pay-frequencies",
        earnType: "/earn-types",
        department: "/department",
        adddepartment: "/add-department",
        updatedepartment: "/update-department",
        rolesAll: "/employee-roles?roleType=all",
        accessRoles: "/employee-access",
        allDepartments: "/departments?&include=employee-count,location-count",
        departmentEmployees: "/employees?filterby=deptId&filtertext=",
        location: "/locations?include=employee-count,dept-count,address",
        editlocation: "/location",
        employeeRoles: "/employee-roles",
        locationEmployees: "/employees?filterby=location&filtertext=",
        getSetRequest: "/employeesbyname",
        assignRole: "/assign-role",
        RemindersRequest: "/reminders",
        roles: "/roles",
        assignedRole: "/assigned-roles",
        payroll: '/payroll',
        empChange: "/employment-change?effectiveDate=",
        jobs: "/jobs",
        reportsAnalytics: "/employee-roles?roleType=reports&offset=0&limit=10&sortOrder=asc",
        reportsAnalyticsPut: "/employee-roles?roleType=reports",
        displaychange: "/display-change-history-details?effectiveDate=",
        displaychangehistory: "/display-change-history",
        fetchCutomFields: "fetchCustomFieldsByemployeeId",
        insertCustomFields: "insertCustomFields",
        updateCustomChanges : "updateCustomChanges",
        deleteCustomChanges : "deleteCustomChanges",
        isCustomChangeAnswered : "custom-change-answered",
        uploadCustomChanges : "upload",
        storeUploadData : "storeUploadData",
        customFields : "custom-fields",
        update : "update",
        reports:"/reports",
        shfcReports: "/sfho-report",
        updateJob: "/update-preliminary-employees",
        updateEthnicity: "/update-ethnicity",
        preliminaryAuditReport : '/preliminary-audit-report'
    }
};
